param(
  [string]$Root = "C:\seller-app\backend"
)

$ErrorActionPreference = "Stop"

$dstDir = Join-Path $Root "scripts\_registry\hampden"
$installDir = Join-Path $dstDir "_install"
New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
New-Item -ItemType Directory -Force -Path $installDir | Out-Null

$pyPath   = Join-Path $dstDir "indexpdf_extract_hampden_rg370rp_mtg_v1.py"
$runPath  = Join-Path $dstDir "Run-Extract-Hampden-MTG-RG_v1_PS51SAFE.ps1"

# ---------- Python extractor (line array; no here-strings) ----------
$py = @(
'#!/usr/bin/env python3',
'from __future__ import annotations',
'',
'"""',
'Hampden Registry (Recorded Land / RG370RP) Index-PDF extractor (MTG packet)',
'Bible rules enforced:',
'- bounded zones only (no full-page parse)',
'- doc_type from page 1 header zone (top-left) only',
'- row reconstruction by Y-band clustering (not splitlines)',
'- multi-property safe via property_refs[]',
'- safe page-break continuation handling',
'"""',
'',
'import argparse, json, os, re, sys, hashlib',
'from datetime import datetime, timezone',
'from typing import Dict, List, Any, Tuple, Optional',
'',
'try:',
'    import pdfplumber',
'except Exception:',
'    print("[fatal] Missing dependency pdfplumber. Install with: pip install pdfplumber", file=sys.stderr)',
'    raise',
'',
'DATE_RE = re.compile(r"^(?P<mdy>\d{2}-\d{2}-\d{4})\s+(?P<hms>\d{1,2}:\d{2}:\d{2}[ap])\s+(?P<book>\d+)\s+(?P<page>\d+)\s+(?P<inst>\d+)\b")',
'DOC_TYPES_RE = re.compile(r"DOC TYPES\.+\s*([A-Z0-9]+)\b")',
'',
'def sha1_hex(s: str) -> str:',
'    return hashlib.sha1(s.encode("utf-8")).hexdigest()',
'',
'def now_run_id() -> str:',
'    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "__hampden__indexpdf_v1"',
'',
'def parse_money(s: str) -> Optional[float]:',
'    s = (s or "").strip()',
'    if not s:',
'        return None',
'    s = s.replace(",", "")',
'    try:',
'        return float(s)',
'    except:',
'        return None',
'',
'def words_in_bbox(page, bbox: Tuple[float,float,float,float]) -> List[Dict[str, Any]]:',
'    try:',
'        return page.within_bbox(bbox).extract_words(keep_blank_chars=False, use_text_flow=False)',
'    except Exception:',
'        return []',
'',
'def cluster_rows(words: List[Dict[str, Any]], y_tol: float = 2.8) -> List[List[Dict[str, Any]]]:',
'    rows: List[List[Dict[str, Any]]] = []',
'    for w in sorted(words, key=lambda x: (x.get("top", 0), x.get("x0", 0))):',
'        y = float(w.get("top", 0))',
'        placed = False',
'        for r in rows:',
'            ry = float(r[0].get("top", 0))',
'            if abs(y - ry) <= y_tol:',
'                r.append(w)',
'                placed = True',
'                break',
'        if not placed:',
'            rows.append([w])',
'    for r in rows:',
'        r.sort(key=lambda x: float(x.get("x0", 0)))',
'    return rows',
'',
'def row_text(row: List[Dict[str, Any]]) -> str:',
'    return " ".join([w.get("text","") for w in row]).strip()',
'',
'def extract_doc_type_code(pdf) -> str:',
'    p0 = pdf.pages[0]',
'    w, h = p0.width, p0.height',
'    header_bbox = (0, 0, w*0.62, h*0.28)  # page 1 top-left only',
'    words = words_in_bbox(p0, header_bbox)',
'    txt = " ".join([w.get("text","") for w in sorted(words, key=lambda x:(x.get("top",0), x.get("x0",0)))])',
'    m = DOC_TYPES_RE.search(txt)',
'    return m.group(1) if m else ""',
'',
'def classify_registry_office(pdf) -> str:',
'    p0 = pdf.pages[0]',
'    w, h = p0.width, p0.height',
'    top_bbox = (0, 0, w, h*0.12)',
'    words = words_in_bbox(p0, top_bbox)',
'    txt = " ".join([w.get("text","") for w in sorted(words, key=lambda x:(x.get("top",0), x.get("x0",0)))])',
'    t = txt.upper()',
'    if "LAND REGISTRATION" in t or "REGISTERED LAND" in t or "LC150RP" in t:',
'        return "REGISTERED_LAND"',
'    return "RECORDED_LAND"',
'',
'def build_event_id(county: str, registry_office: str, doc_type_code: str, recording: Dict[str, Any]) -> str:',
'    seed = "|".join([',
'        "MA","registry","indexpdf",county.lower(),registry_office,',
'        (doc_type_code or ""),',
'        (recording.get("recording_date") or ""),',
'        (recording.get("book") or ""),',
'        (recording.get("page") or ""),',
'        (recording.get("instrument_number_raw") or "")',
'    ])',
'    return "MA|registry|indexpdf|" + county.lower() + "|" + sha1_hex(seed)',
'',
'def normalize_party_name(s: str) -> str:',
'    s = re.sub(r"\s+", " ", (s or "").strip())',
'    s = s.replace("“","").replace("”","").replace(chr(34),"")',
'    return s.upper()',
'',
'def main():',
'    ap = argparse.ArgumentParser()',
'    ap.add_argument("--pdf", required=True)',
'    ap.add_argument("--out", required=True)',
'    ap.add_argument("--audit", required=True)',
'    ap.add_argument("--run-id", default="")',
'    ap.add_argument("--county", default="hampden")',
'    args = ap.parse_args()',
'',
'    in_pdf = args.pdf',
'    run_id = args.run_id.strip() or now_run_id()',
'    county = args.county.strip().lower()',
'',
'    os.makedirs(os.path.dirname(args.out), exist_ok=True)',
'    os.makedirs(os.path.dirname(args.audit), exist_ok=True)',
'',
'    stats = {',
'        "run_id": run_id,',
'        "pdf": in_pdf,',
'        "events_written": 0,',
'        "pages": 0,',
'        "doc_type_code": None,',
'        "registry_office": None,',
'        "warnings": [],',
'        "quarantined_fragments": 0,',
'        "continuation_rows_attached": 0',
'    }',
'',
'    events: List[Dict[str, Any]] = []',
'',
'    with pdfplumber.open(in_pdf) as pdf:',
'        stats["pages"] = len(pdf.pages)',
'        registry_office = classify_registry_office(pdf)',
'        stats["registry_office"] = registry_office',
'        doc_type_code = extract_doc_type_code(pdf)',
'        stats["doc_type_code"] = doc_type_code or None',
'        if not doc_type_code:',
'            stats["warnings"].append("DOC_TYPE_CODE_NOT_FOUND_PAGE1_HEADER")',
'',
'        current_event: Optional[Dict[str, Any]] = None',
'        header_context: Optional[Dict[str, Any]] = None',
'',
'        for pi, page in enumerate(pdf.pages):',
'            w, h = page.width, page.height',
'            body_bbox = (0, h*0.20, w, h*0.94)',
'            words = words_in_bbox(page, body_bbox)',
'            rows = cluster_rows(words, y_tol=2.8)',
'',
'            for row in rows:',
'                txt = row_text(row)',
'                if not txt:',
'                    continue',
'',
'                m = DATE_RE.match(txt)',
'                if m:',
'                    if current_event is not None:',
'                        events.append(current_event)',
'',
'                    recording_date_raw = m.group("mdy")',
'                    time_raw = m.group("hms")',
'                    book = m.group("book")',
'                    page_no = m.group("page")',
'                    inst = m.group("inst")',
'',
'                    try:',
'                        dt = datetime.strptime(recording_date_raw, "%m-%d-%Y")',
'                        recording_date = dt.strftime("%Y-%m-%d")',
'                    except Exception:',
'                        recording_date = None',
'',
'                    recording = {',
'                        "recorded_at_raw": recording_date_raw + " " + time_raw,',
'                        "recording_date_raw": recording_date_raw,',
'                        "recording_date": recording_date,',
'                        "recording_time_raw": time_raw,',
'                        "recording_time": time_raw,',
'                        "book": book,',
'                        "page": page_no,',
'                        "instrument_number_raw": inst,',
'                        "seq": None',
'                    }',
'',
'                    header_context = {"recording": recording, "page_index": pi}',
'                    event_id = build_event_id(county, registry_office, doc_type_code, recording)',
'',
'                    current_event = {',
'                        "schema": {"name": "equitylens.registry_event", "version": "mim_v1_0"},',
'                        "event_id": event_id,',
'                        "event_type": "MORTGAGE",',
'                        "county": county,',
'                        "registry_system": "registry_index_pdf",',
'                        "registry_office": registry_office,',
'                        "doc_type_code": doc_type_code or None,',
'                        "doc_type_desc": "MORTGAGE" if (doc_type_code or "").upper() == "MTG" else None,',
'                        "source": {',
'                            "run_id": run_id,',
'                            "as_of_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),',
'                            "uri": "file://" + os.path.abspath(in_pdf)',
'                        },',
'                        "recording": recording,',
'                        "parties": [],',
'                        "property_refs": [],',
'                        "consideration": None,',
'                        "flags": [],',
'                        "attach": {',
'                            "status": "UNKNOWN",',
'                            "property_id": None,',
'                            "method": None,',
'                            "confidence": None,',
'                            "evidence": {},',
'                            "flags": [],',
'                            "attach_scope": "MULTI"',
'                        }',
'                    }',
'                    continue',
'',
'                # page-break continuation: first entry may miss the DATE/BOOK/PAGE/INST row',
'                if current_event is None and header_context is not None:',
'                    if ("Town:" in txt and "Addr:" in txt) or re.match(r"^\\s*\\d+\\s+[PC]\\s+", txt):',
'                        recording = header_context["recording"]',
'                        event_id = build_event_id(county, registry_office, doc_type_code, recording)',
'                        current_event = {',
'                            "schema": {"name": "equitylens.registry_event", "version": "mim_v1_0"},',
'                            "event_id": event_id,',
'                            "event_type": "MORTGAGE",',
'                            "county": county,',
'                            "registry_system": "registry_index_pdf",',
'                            "registry_office": registry_office,',
'                            "doc_type_code": doc_type_code or None,',
'                            "doc_type_desc": "MORTGAGE" if (doc_type_code or "").upper() == "MTG" else None,',
'                            "source": {',
'                                "run_id": run_id,',
'                                "as_of_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),',
'                                "uri": "file://" + os.path.abspath(in_pdf)',
'                            },',
'                            "recording": recording,',
'                            "parties": [],',
'                            "property_refs": [],',
'                            "consideration": None,',
'                            "flags": ["PAGEBREAK_CONTINUATION_START"],',
'                            "attach": {',
'                                "status": "UNKNOWN",',
'                                "property_id": None,',
'                                "method": None,',
'                                "confidence": None,',
'                                "evidence": {},',
'                                "flags": [],',
'                                "attach_scope": "MULTI"',
'                            }',
'                        }',
'                        stats["continuation_rows_attached"] += 1',
'',
'                if current_event is None:',
'                    stats["quarantined_fragments"] += 1',
'                    continue',
'',
'                if "Town:" in txt and "Addr:" in txt:',
'                    town_m = re.search(r"Town:\\s*([A-Z \\-\\x27]+)\\s+Addr:\\s*(.+)$", txt)',
'                    if town_m:',
'                        town = town_m.group(1).strip()',
'                        addr = town_m.group(2).strip()',
'                        unit_hint = None',
'                        um = re.search(r"\\b(UNIT|APT|#|STE|SUITE)\\s*([A-Z0-9\\-]+)\\b", addr.upper())',
'                        if um:',
'                            unit_hint = (um.group(1) + " " + um.group(2)).strip()',
'                        current_event["property_refs"].append({',
'                            "ref_index": len(current_event["property_refs"]) + 1,',
'                            "town_raw": town,',
'                            "address_raw": addr,',
'                            "address_norm": None,',
'                            "unit_hint": unit_hint,',
'                            "lot_ref_raw": None,',
'                            "lot_ref_structured": None,',
'                            "ref_anchor_type": "ADDRESS",',
'                            "attach_status": "UNKNOWN",',
'                            "attach_confidence": None,',
'                            "evidence": {"page_index": pi}',
'                        })',
'                    continue',
'',
'                if current_event.get("consideration") is None:',
'                    money_m = re.search(r"(\\d{1,3}(?:,\\d{3})*\\.\\d{2})", txt)',
'                    if money_m:',
'                        raw = money_m.group(1)',
'                        amt = parse_money(raw)',
'                        if amt is not None:',
'                            current_event["consideration"] = {',
'                                "raw_text": raw,',
'                                "amount": amt,',
'                                "parse_status": "PARSED",',
'                                "flags": [],',
'                                "source": "INDEXPDF"',
'                            }',
'',
'                pm = re.match(r"^\\s*(\\d+)\\s+([PC])\\s+(.+)$", txt)',
'                if pm:',
'                    side = pm.group(1).strip()',
'                    ent_code = pm.group(2).strip()',
'                    name = pm.group(3).strip()',
'                    current_event["parties"].append({',
'                        "role": "ROLE_" + side,',
'                        "name_raw": name,',
'                        "name_norm": normalize_party_name(name),',
'                        "entity_type": "PERSON" if ent_code == "P" else "ORG",',
'                        "mailing_address_raw": None',
'                    })',
'                    continue',
'',
'        if current_event is not None:',
'            events.append(current_event)',
'',
'    with open(args.out, "w", encoding="utf-8") as f:',
'        for ev in events:',
'            f.write(json.dumps(ev, ensure_ascii=False) + "\\n")',
'    stats["events_written"] = len(events)',
'',
'    with open(args.audit, "w", encoding="utf-8") as f:',
'        json.dump(stats, f, indent=2)',
'',
'    print("[done] wrote", stats["events_written"], "events")',
'    print("[audit]", args.audit)',
'',
'if __name__ == "__main__":',
'    main()'
)

Set-Content -Path $pyPath -Value $py -Encoding UTF8
Write-Host "[ok] wrote $pyPath"

# ---------- Runner ----------
$run = @(
'param(',
'  [string]$Root = "C:\seller-app\backend",',
'  [string]$Pdf = "C:\seller-app\backend\publicData\registry\hampden\incoming\OTR\hamden_mortgage_ 01-16-21-01-16-26.pdf"',
')',
'$ErrorActionPreference = "Stop"',
'',
'$runTs = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")',
'$runId = "${runTs}__hampden__indexpdf_v1"',
'',
'$workRoot = Join-Path $Root ("publicData\registry\hampden\_work\INDEXPDF_EXTRACT_v1\" + $runId)',
'$canonDir = Join-Path $workRoot "canon"',
'$auditDir = Join-Path $workRoot "audit"',
'New-Item -ItemType Directory -Force -Path $canonDir | Out-Null',
'New-Item -ItemType Directory -Force -Path $auditDir | Out-Null',
'',
'$outNdjson = Join-Path $canonDir ("events__HAMPDEN__INDEXPDF__MTG__" + $runId + ".ndjson")',
'$auditJson = Join-Path $auditDir ("audit__HAMPDEN__INDEXPDF__MTG__" + $runId + ".json")',
'',
'$py = Join-Path $Root "scripts\_registry\hampden\indexpdf_extract_hampden_rg370rp_mtg_v1.py"',
'if (!(Test-Path $py)) { throw "Missing extractor script: $py" }',
'if (!(Test-Path $Pdf)) { throw "Missing input PDF: $Pdf" }',
'',
'Write-Host "[start] Hampden RG370RP MTG extract v1"',
'Write-Host "[run]   $runId"',
'Write-Host "[in]    $Pdf"',
'Write-Host "[out]   $outNdjson"',
'Write-Host "[audit] $auditJson"',
'',
'python $py --pdf "$Pdf" --out "$outNdjson" --audit "$auditJson" --run-id "$runId" --county "hampden"',
'',
'Write-Host "[done] extraction complete"'
)

Set-Content -Path $runPath -Value $run -Encoding UTF8
Write-Host "[ok] wrote $runPath"

Write-Host "[note] one-time dependency: pip install pdfplumber"
Write-Host "[done] creator complete"
