/**
 * batchGeocodeSchoolDistricts.js
 *
 * Converts school district SHP/DBF files → usable:
 *   1. districtShapes.geojson
 *   2. districtCache.json
 *   3. districtLookup.js (lookup-ready format)
 */

const fs = require("fs");
const path = require("path");
const shp = require("shpjs");
const centroid = require("@turf/centroid").default;

// --------------------------------------------------
// INPUT PATHS
// --------------------------------------------------
const UNZIPPED_DIR = path.join(
  __dirname,
  "../../publicData/schoolData/unzipped"
);

const SHP_FILE = path.join(UNZIPPED_DIR, "SCHOOLDISTRICTS_POLY.shp");
const DBF_FILE = path.join(UNZIPPED_DIR, "SCHOOLDISTRICTS_POLY.dbf");

// --------------------------------------------------
// OUTPUT PATHS
// --------------------------------------------------
const OUTPUT_DIR = path.join(__dirname, "../../publicData/schoolData");

const OUT_GEOJSON = path.join(OUTPUT_DIR, "districtShapes.geojson");
const OUT_CACHE = path.join(OUTPUT_DIR, "districtCache.json");
const OUT_LOOKUP = path.join(OUTPUT_DIR, "districtLookup.js");

// --------------------------------------------------
(async () => {
  try {
    console.log("📘 Reading school district SHP/DBF…");

    const bufShp = fs.readFileSync(SHP_FILE);
    const bufDbf = fs.readFileSync(DBF_FILE);

    console.log("🔄 Converting SHP → GeoJSON…");
    const geo = await shp.combine([bufShp, bufDbf]);

    if (!geo || !geo.features) {
      console.log("❌ No features in school district dataset");
      return;
    }

    console.log(`📍 Found ${geo.features.length} school district polygons`);

    const cache = [];
    const geojsonOut = {
      type: "FeatureCollection",
      features: [],
    };

    for (const f of geo.features) {
      const cent = centroid(f).geometry.coordinates;

      const district = {
        id: f.properties?.DIST_ID || f.properties?.ID || null,
        name: f.properties?.DIST_NAME || f.properties?.NAME || null,
        centroidLng: cent[0],
        centroidLat: cent[1],
        geometry: f.geometry,
      };

      // add to cache
      cache.push(district);

      // add Feature to GeoJSON
      geojsonOut.features.push({
        type: "Feature",
        geometry: f.geometry,
        properties: {
          id: district.id,
          name: district.name,
        },
      });
    }

    console.log("💾 Saving district shapes…");
    fs.writeFileSync(OUT_GEOJSON, JSON.stringify(geojsonOut, null, 2));

    console.log("💾 Saving district cache…");
    fs.writeFileSync(OUT_CACHE, JSON.stringify(cache, null, 2));

    console.log("💾 Generating districtLookup.js…");

    const lookupCode = `
// districtLookup.js — FAST polygon-based lookup
// Auto-generated by batchGeocodeSchoolDistricts.js

const districts = require("./districtCache.json");
const booleanPointInPolygon = require("@turf/boolean-point-in-polygon").default;

function findSchoolDistrict(lat, lng) {
  const pt = { type: "Point", coordinates: [lng, lat] };

  for (const d of districts) {
    if (!d.geometry) continue;
    try {
      if (booleanPointInPolygon(pt, { type: "Feature", geometry: d.geometry })) {
        return { id: d.id, name: d.name };
      }
    } catch (err) {}
  }
  return null;
}

module.exports = { findSchoolDistrict };
`;

    fs.writeFileSync(OUT_LOOKUP, lookupCode);

    console.log("✅ School district geocoding complete!");

  } catch (err) {
    console.error("❌ Error:", err);
  }
})();




{
  "type"; "FeatureCollection",
  "features"; [
    {
      "type": "Feature",
      "properties": {
        "ZONE": "R1",
        "DESC": "Single Family Residential"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-71.6000, 42.3400],
            [-71.5900, 42.3400],
            [-71.5900, 42.3500],
            [-71.6000, 42.3500],
            [-71.6000, 42.3400]
          ]
        ]
      }
    }
  ]
}

